blissful_network/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group_list/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path(
        'posts/comments/<int:comment_id>/delete/',
        views.comment_delete, name='delete_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=30)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.text

class Comment(models.Model):
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Текст вашего комментария'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from . forms import PostForm, CommentForm
from .models import Post, Group, Comment, Follow, User


def index(request):
    post_list = Post.objects.all().order_by('-pub_date')

    paginator = Paginator(post_list, 10)

    page_number = request.GET.get('page')

    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)

def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)

    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

def profile(request, username):
    user_posts = Post.objects.filter(author__username=username)
    c_posts = user_posts.count()
    following = False
    if request.user.is_authenticated:
        following = request.user.follower.filter(author__username=username).exists()
    paginator = Paginator(user_posts, 10)

    page_number = request.GET.get('page')

    page_obj = paginator.get_page(page_number)

    context = {
        'username': username,
        'c_posts': c_posts,
        'user_posts': user_posts,
        'page_obj': page_obj,
        'following': following,
        'author': request.user,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    c_posts = Post.objects.filter(author=post.author).count()
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'c_posts': c_posts,
        'comments': comments,
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)

@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        temp_form = form.save(commit=False)
        temp_form.author = request.user
        temp_form.save()
        return redirect(
            'posts:profile', temp_form.author
        )
    return render(request, template, {'form': form})


def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect(
            'posts:post_detail', post_id
        )
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect(
            'posts:post_detail', post_id
        )
    return render(request, template, {
        'form': form, 'is_edit': True, 'post': post
    })


def page_not_found(request, exception):
    return render(request, 'core/404.html', {'path': request.path}, status=404)

@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = get_object_or_404(Post, pk=post_id)
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    title = 'Публикации избранных авторов'
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    follow_author = get_object_or_404(User, username=username)
    if follow_author != request.user and (
        not request.user.follower.filter(author=follow_author).exists()
    ):
        Follow.objects.create(
            user=request.user,
            author=follow_author
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    follow_author = get_object_or_404(User, username=username)
    data_follow = request.user.follower.filter(author=follow_author)
    if data_follow.exists():
        data_follow.delete()
    return redirect('posts:profile', username)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author == request.user:
        post.delete()
    return redirect('posts:profile', post.author.username)


@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if comment.author == request.user:
        comment.delete()
    return redirect('posts:post_detail', post_id=comment.post.pk)

templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
{% if is_edit %}
<title>Сохранить запись</title>
{% else %}
<title>Добавить запись</title>
{% endif %}
{% endblock %}
{% load user_filters %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    {% if is_edit %}
                    Сохранить запись
                    {% else %}
                    Добавить запись
                    {% endif %}
                </div>
                <div class="card-body">

                    {% if is_edit %}
                    <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post.pk %}"></form>
                        {% else %}
                        <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
                            {% endif %}
                            {% csrf_token %}

                            {% for field in form %}
                            <div class="form-group row my-3 p-3 textarea">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                    <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                {{ field|addclass:'form-control' }}
                                {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                    {{ field.help_text|safe }}
                                </small>
                                {% endif %}
                            </div>
                            {% endfor %}
                            <div class="d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">
                                    {% if is_edit %}
                                    Сохранить
                                    {% else %}
                                    Добавить
                                    {% endif %}
                                </button>
                            </div>
                        </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %} 
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% load thumbnail %}
  {% for post in page_obj %}
  <div class="container col-lg-9 col-sm-12">
    <ul>
    <li>
      <b>Автор:</b>
      <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
    </li>
    <li>
      <b>Дата публикации:</b> {{ post.pub_date|date:"d E Y" }}
    </li>
    {% if post.group %}
    <li>
      <p><b>Группа:</b> 
      <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a></p>
    </li>
    {% endif %}
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaks }}</p>
    <a href="{% url 'posts:post_detail' post.pk %}">(подробная информация)</a>    
    {% if not forloop.last %}<hr>{% endif %}
  </div>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

templates/posts/group_list.html
{% extends 'base.html' %}

{% block content %}
  <h3>Сообщество: {{ group.title }}</h3>
  <p>Описание сообщества: {{ group.description }}</p>

  <div class="container py-5">
    {% for post in posts %}
      <article>
        <ul>
          <li>Автор: <a href="{% url 'posts:profile' post.author %}">{{ post.author.username }}</a></li>
          <li>Дата публикации: {{ post.pub_date }}</li>
        </ul>
        <p>{{ post.text }}</p>
      </article>
      <hr>
    {% endfor %}
  </div>
{% endblock %}

templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ title }}</h1>
  {% for post in page_obj %}
    <ul>
      <li>
        <b>Автор: </b>
        <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    {% if post.group %}
      <a href="{% url 'posts:group_list' slug=post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}<title>Пост {{ post.text|truncatechars:30 }} </title>{% endblock %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
<div class="container col-lg-9 col-sm-12">
    <div class="row">
        <aside class="col-12 col-md-4">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <b>Дата публикации:</b><br> {{ post.pub_date|date:"d E Y" }}
                </li>
                {% if post.group %}
                <li class="list-group-item">
                    <b>Группа:</b>
                    <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
                </li>
                {% endif %}
                <li class="list-group-item">
                    <b>Автор:</b>
                    <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
                </li>
                <li class="list-group-item">
                    <b>Всего постов автора:</b> {{ post.author.posts.count }}
                </li>
            </ul>
        </aside>
        <article class="col-12 col-md-8">
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
                {{ post.text|linebreaks }}
            </p>
            {% if post.author == user %}
                <a href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a>&nbsp;&nbsp;&nbsp;
                <a href="{% url 'posts:post_delete' post.pk %}">удалить запись</a>
            {% endif %}
            {% if user.is_authenticated %}
            <div class="card my-4">
                <h6 class="card-header">Добавить комментарий:</h6>
                <div class="card-body">
                    <form method="post" action="{% url 'posts:add_comment' post.id %}">
                        {% csrf_token %}
                        <div class="form-group mb-4 textarea">
                            {{ form.text|addclass:"form-control" }}
                        </div>
                        <button type="submit" class="btn btn-primary">Отправить</button>
                    </form>
                </div>
            </div>
            {% endif %}
            {% for comment in comments %}
            <div class="media mb-4">
                <div class="media-body">
                    <h5 class="mt-0">
                        <a href="{% url 'posts:profile' comment.author.username %}">
                            {{ comment.author.get_full_name }}
                        </a>
                    </h5>
                    <p>
                        {{ comment.text }}
                        {% if post.author == user %}
                        <br>
                        <a href="{% url 'posts:delete_comment' comment.pk %}">удалить запись</a>
                        {% endif %}
                        {% if not forloop.last %}
                    <hr>
                    {% endif %}
                    </p>
                </div>
            </div>
            {% endfor %}
        </article>
    </div>
</div>
{% endblock %}

templates/posts/profile.html
{% extends "base.html" %}
{% block title %}<title>Профайл пользователя {{ username }} </title>{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container col-lg-9 col-sm-12">
  <h2>Все посты пользователя {{ username }} </h2>
  <h3>Всего постов: {{ c_posts }}</h3>
  {% if user.is_authenticated %}
      {% if username != user.username %}
          {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' username %}" role="button"
          >
            Отписаться
          </a>
          {% else %}
              <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' username %}" role="button"
              >
                Подписаться
              </a>
          {% endif %}
      {% endif %}
  {% endif %}
   <br><br>
  {% for post in page_obj %}
    <article>
    <ul>
      <li>
        Автор: {{ username }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
        {% if post.group %}
        <li>
            <p>Группа:
            <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a></p>
        </li>
        {% endif %}
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
    {{ post.text|linebreaks }}
    <a href="{% url 'posts:post_detail' post.pk %}">(подробная информация)</a>
    </p>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}